// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ6oLhKRDmIATTddumzCkc5mqE3ad4fxU',
    appId: '1:636235891170:web:b6efb797ec8a1bb4ebb9bb',
    messagingSenderId: '636235891170',
    projectId: 'servicereservationapp',
    authDomain: 'servicereservationapp.firebaseapp.com',
    storageBucket: 'servicereservationapp.firebasestorage.app',
    measurementId: 'G-JP66Y36S9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeHL82vdrWbz9k6oBepbjl18biumcqS-w',
    appId: '1:636235891170:android:54e679fa16c8d952ebb9bb',
    messagingSenderId: '636235891170',
    projectId: 'servicereservationapp',
    storageBucket: 'servicereservationapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFlVVc7v6Zc48MNi9Py9hei0eo-xQqB0Q',
    appId: '1:636235891170:ios:14bf41d2691cbffdebb9bb',
    messagingSenderId: '636235891170',
    projectId: 'servicereservationapp',
    storageBucket: 'servicereservationapp.firebasestorage.app',
    iosBundleId: 'com.aslmmovic.serviceReservationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFlVVc7v6Zc48MNi9Py9hei0eo-xQqB0Q',
    appId: '1:636235891170:ios:14bf41d2691cbffdebb9bb',
    messagingSenderId: '636235891170',
    projectId: 'servicereservationapp',
    storageBucket: 'servicereservationapp.firebasestorage.app',
    iosBundleId: 'com.aslmmovic.serviceReservationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ6oLhKRDmIATTddumzCkc5mqE3ad4fxU',
    appId: '1:636235891170:web:93279149641b74e1ebb9bb',
    messagingSenderId: '636235891170',
    projectId: 'servicereservationapp',
    authDomain: 'servicereservationapp.firebaseapp.com',
    storageBucket: 'servicereservationapp.firebasestorage.app',
    measurementId: 'G-1SG0D9E6WX',
  );
}
